name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test-linux:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Check
      run: cargo check
    - name: Build
      run: cargo build --all
    - name: Test
      run: cargo test --all
  clippy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Install clippy (base toolchain)
      run: rustup component add clippy
    - name: Run clippy
      run: cargo clippy --all
  rustfmt:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Install rustfmt (base toolchain)
      run: rustup component add rustfmt
    - name: Run rustfmt
      run: cargo fmt --all
